vpk_file: /home/madison/.local/share/Steam/steamapps/common/Team Fortress 2/tf/tf2_misc_dir.vpk
#vpk_file: tf2_misc_dir.vpk
color_shift:
  mode: MATCH_TARGET  # Can be MATCH_TARGET, PRESERVE_FEEL, or RANDOM (default is MATCH_TARGET)
pcf_files:
  - file: medicgun_beam.pcf
  - file: medicgun_attrib.pcf
  - file: rocketbackblast.pcf
  - file: explosion.pcf
  - file: rockettrail.pcf